package com.silentgo.shiro;

/**
 * Created by teddy on 2015/7/18.
 */
public class Dict {

    public static final String SECURITY_KEY = "SECURITY_KEY";

    public static final String PASSWORD_ERROR_COUNT = "PASSWORD_ERROR_COUNT";

    public static final String PASSWORD_ERROR_RETRY_HOUR = "PASSWORD_ERROR_RETRY_HOUR";

    public static final String SHIRO_CREDENTIALS_MATCHER_HASHALGORITHMNAME = "SHIRO_CREDENTIALS_MATCHER_HASHALGORITHMNAME";

    public static final String SHIRO_CREDENTIALS_MATCHER_HASHITERATIONS = "SHIRO_CREDENTIALS_MATCHER_HASHITERATIONS";

    public static final String SHIRO_CREDENTIALS_MATCHER_STOREDCREDENTIALSHEXENCODED = "SHIRO_CREDENTIALS_MATCHER_STOREDCREDENTIALSHEXENCODED";

    public static final String SHIRO_USERREALM_CACHINGENABLED = "SHIRO_USERREALM_CACHINGENABLED";

    public static final String SHIRO_SESSION_GLOBALSESSIONTIMEOUT = "SHIRO_SESSION_GLOBALSESSIONTIMEOUT";

    public static final String SHIRO_SESSION_DELETEINVALIDSESSIONS = "SHIRO_SESSION_DELETEINVALIDSESSIONS";
    public static final String SHIRO_SESSION_VALIDATIONSCHEDULERENABLED = "SHIRO_SESSION_VALIDATIONSCHEDULERENABLED";
    public static final String SHIRO_SESSION_IDCOOKIEENABLED = "SHIRO_SESSION_IDCOOKIEENABLED";
    public static final String SHIRO_SESSION_COOKIENAME = "SHIRO_SESSION_COOKIENAME";
    public static final String SHIRO_SESSION_IDCOOKIE_HTTPONLY = "SHIRO_SESSION_IDCOOKIE_HTTPONLY";
    public static final String SHIRO_SESSION_IDCOOKIE_MAXAGE = "SHIRO_SESSION_IDCOOKIE_MAXAGE";
    public static final String SHIRO_SESSION_REMEMBER_ME_HTTPONLY = "SHIRO_SESSION_REMEMBER_ME_HTTPONLY";
    public static final String SHIRO_SESSION_REMEMBER_ME_MAXAGE = "SHIRO_SESSION_REMEMBER_ME_MAXAGE";

    public static final String SHIRO_SESSION_VALIDATIONINTERVAL = "SHIRO_SESSION_VALIDATIONINTERVAL";

    public static final String SHIRO_SESSION_REMEMBER_COOKIENAME = "SHIRO_SESSION_REMEMBER_COOKIENAME";

    public static final String SHIRO_SESSION_ACTIVE_NAME = "SHIRO_SESSION_ACTIVE_NAME";

}

